# This is a config for E2B sandbox template.
# You can use template ID (4ln11kl33bettsoxgp9h) or template name (siteforge-ai-nextjs-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("siteforge-ai-nextjs-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("siteforge-ai-nextjs-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('siteforge-ai-nextjs-test-2')

team_id = "4f7c70fe-48b4-4ac8-8b82-5099646d9181"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "siteforge-ai-nextjs-test-2"
template_id = "4ln11kl33bettsoxgp9h"
